# apiVersion: v1
# kind: Secret
# metadata:
#   name: api-secrets
#   namespace: oficina
# type: Opaque
# stringData:
#   DB_HOST: "<endpoint-do-rds>"
#   DB_PORT: "3306"
#   DB_USER: "lameque"
#   DB_PASSWORD: "lameque123"
#   DB_NAME: "oficina_fase1"

#   JWT_SECRET: "<MESMO_SEGREDO_DA_LAMBDA>"
#   JWT_ISSUER: "oficina-auth"
#   JWT_AUDIENCE: "oficina-api"

apiVersion: v1
kind: Secret
metadata:
  name: ordem-servico-secrets
  namespace: oficina
type: Opaque
stringData:
  USER_DB: "<USER_DB>"
  PASSWORD_DB: "<PASSWORD_DB>"
  HOST_DB: "<HOST_DB>"
  PORT_DB: "<PORT_DB>"
  DATABASE: "<DATABASE>"
  SECRET_KEY: "<SECRET_KEY>"
  ALGORITHM: "<ALGORITHM>"
  JWT_ISSUER: "<JWT_ISSUER>"
  JWT_AUDIENCE: "<JWT_AUDIENCE>"
  URL_API_EXECUCAO: "<URL_API_EXECUCAO>"