apiVersion: v1
kind: Service
metadata:
  name: oficina-ordem-servico-api-service
  namespace: oficina
spec:
  type: LoadBalancer
  selector:
    app: oficina-ordem-servico-api
  ports:
    - port: 8001
      targetPort: 8001
